apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ffw-funk

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - ingressroute.yaml
  - secrets.yaml
  - redis-auth-ffw.yaml

commonLabels:
  app.kubernetes.io/name: ffw-funk
  app.kubernetes.io/part-of: feuerwehr
