apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ffw-funk-secrets
  namespace: ffw-funk
spec:
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: infisical-operator
      secretsScope:
        envSlug: prod
        projectSlug: homelab-ei-fj
        secretsPath: /ffw-funk
  hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api
  managedKubeSecretReferences:
    - secretName: ffw-funk-secrets
      secretNamespace: ffw-funk
      secretType: Opaque
  resyncInterval: 60

